// Builds data/dataset.js from:
//   data/planetarycouncil.json — incidents from warcrimes.planetarycouncil.org (primary)
//   data/research.json         — extra incidents, government reactions, BBC headlines & context
// Run: npm run build:data
// Refresh the Planetary Council copy with: npm run build:data -- --pull ../warcrimes/data.json

import { readFile, writeFile } from 'node:fs/promises';

const pullFrom = process.argv.find((a, i) => process.argv[i - 1] === '--pull');
if (pullFrom) {
  const pc = JSON.parse(await readFile(pullFrom, 'utf8'));
  const incidents = pc.incidents.filter((i) => ['main', 'closers'].includes(i.section) || i.id === 'hamas-oct7');
  await writeFile('data/planetarycouncil.json', JSON.stringify({ from: 'https://github.com/PlanetaryCouncil/warcrimes/blob/main/data.json', updated: pc.meta?.updated, incidents }, null, 1));
}

const pc = JSON.parse(await readFile('data/planetarycouncil.json', 'utf8'));
const research = JSON.parse(await readFile('data/research.json', 'utf8'));

// Research entries that describe the same event as a Planetary Council entry.
const SAME = {
  'hind-rajab-2024': 'hind-rajab',
  'nasser-hospital-2025': 'nasser-double-tap',
  'ghf-aid-sites-2025': 'ghf-aid-shootings',
  'wck-convoy-2024': 'wck-strike',
  'flour-massacre-2024': 'flour-massacre',
  'anas-al-sharif-2025': 'anas-al-sharif',
  'al-nasr-babies-2023': 'al-nasr-babies',
  'rafah-medics-2025': 'rafah-paramedics',
  'sde-teiman-2024': 'right-to-rape',
  'detainee-dog-allegations': 'sde-teiman-dogs',
};

// Evidence label per Planetary Council entry (the source data has none).
// documented = admitted by Israel, or video/forensic/multiple independent investigations.
// REVIEW: these are the site's editorial calls; change them here.
const STATUS = {
  'hind-rajab': 'documented', 'nasser-double-tap': 'documented', 'wck-strike': 'documented',
  'rafah-paramedics': 'documented', 'anas-al-sharif': 'documented', 'doha-strike': 'documented',
  'hamas-oct7': 'documented', 'jenin-execution': 'documented', 'journalist-legs': 'documented',
  'genocidal-rhetoric': 'documented', 'terrorist-label': 'documented',
  'hospital-rocket-jump': 'reported', 'ghf-aid-shootings': 'reported', 'flour-massacre': 'reported',
  'al-nasr-babies': 'reported', 'right-to-rape': 'reported', 'children-sniped': 'reported',
  'doctors-under-fire': 'reported', 'christians': 'reported', 'human-shields': 'reported',
  'sde-teiman-dogs': 'reported', 'organs-missing': 'alleged', 'baby-cigarette': 'alleged',
};

const MONTHS = { jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6, jul: 7, aug: 8, sep: 9, oct: 10, nov: 11, dec: 12 };
function isoDate(text) {
  let m = text.match(/(\d{4})-(\d{2})-(\d{2})/);
  if (m) return m[0];
  m = text.match(/(\d{1,2})\s+([A-Za-z]{3})[a-z]*\.?\s+(\d{4})/);
  if (m && MONTHS[m[2].toLowerCase()]) return `${m[3]}-${pad(MONTHS[m[2].toLowerCase()])}-${pad(m[1])}`;
  m = text.match(/([A-Za-z]{3})[a-z]*\s+(\d{4})/);
  if (m && MONTHS[m[1].toLowerCase()]) return `${m[2]}-${pad(MONTHS[m[1].toLowerCase()])}-01`;
  return null;
}
const pad = (n) => String(n).padStart(2, '0');

const byPc = new Map();
for (const [rid, pid] of Object.entries(SAME)) byPc.set(pid, research.incidents.find((x) => x.id === rid));

const incidents = pc.incidents.map((i) => {
  const r = byPc.get(i.id);
  return {
    id: i.id,
    title: i.title,
    date: isoDate(i.date) || r?.date || '2023-10-07',
    dateText: i.date,
    place: r?.place || '',
    summary: i.summary,
    notes: i.bullets || [],
    caveat: i.verify || null,
    status: STATUS[i.id] || 'reported',
    sources: i.links.filter((l) => l.tag !== 'propaganda')
      .map((l) => ({ label: `${l.source}${l.headline ? ' – ' + l.headline : ''}`, url: l.url })),
    officialResponse: i.official ? { text: i.official.label, verbatim: true, source: { label: 'source', url: i.official.url } }
      : r?.officialResponse || null,
    reactions: r?.reactions || [],
    origin: 'planetarycouncil',
  };
});

const merged = new Set(Object.keys(SAME));
for (const r of research.incidents) if (!merged.has(r.id)) incidents.push({ ...r, origin: 'research' });
incidents.sort((a, b) => a.date.localeCompare(b.date));

const out = `// GENERATED by tools/build-data.mjs — edit data/*.json, then run \`npm run build:data\`.
// Every quote and headline must be checked against the linked page before launch (see README).
export const SOURCES_CHECKED = false;

export const incidents = ${JSON.stringify(incidents, null, 2)};

export const headlines = ${JSON.stringify(research.headlines, null, 2)};

export const bbcContext = ${JSON.stringify(research.bbcContext, null, 2)};
`;
await writeFile('data/dataset.js', out);
console.log(`dataset.js: ${incidents.length} incidents (${pc.incidents.length} Planetary Council + ${incidents.length - pc.incidents.length} research), ${research.headlines.length} headlines`);
const undated = incidents.filter((x) => !isoDate(x.dateText || x.date));
if (undated.length) console.log('dates guessed for:', undated.map((x) => x.id).join(', '));
